(in-package om)

(defparameter *cb-open-strings* '(28 33 38 43))

(defparameter *nat-harmonic-guide* '((3 31)
                                     (4 28)
                                     (5 24)
                                     (5.5 33.5)
                                     (7 19)
                                     (9 28)
                                     (12 12)
                                     (16 28)
                                     (19 19)
                                     (21.5 33.5)
                                     (24 24)
                                     (28 28)
                                     (31 31)
                                     (33.5 33.5)))